"""SAIL 平台常量。集中定义避免散落各处。"""

from app.domain.scan_run import (
    SCAN_RUN_CANCELLED,
    SCAN_RUN_CREATED,
    SCAN_RUN_FAILED,
    SCAN_RUN_PARTIAL_SUCCEEDED,
    SCAN_RUN_QUEUED,
    SCAN_RUN_RUNNING,
    SCAN_RUN_SUCCEEDED,
    STAGE_ASSEMBLE_CONTEXT,
    STAGE_AI_ANALYZE,
    STAGE_ASSESS_API_SECURITY,
    STAGE_BUILD_CODEQL_DATABASE,
    STAGE_ENRICH_API_DEPTH,
    STAGE_EXTRACT_API_FACTS,
    STAGE_FETCH_SOURCE,
    STAGE_FINALIZE,
    STAGE_FINDING_CANDIDATES,
    STAGE_MERGE_FINDINGS,
    STAGE_PERSIST_RESULTS,
    STAGE_PREFLIGHT,
    STAGE_RUN_CODEQL_VULN_SCAN,
    STAGE_CANCELLED,
    STAGE_FAILED_FINAL,
    STAGE_FAILED_RETRYABLE,
    STAGE_PENDING,
    STAGE_RUNNING,
    STAGE_SKIPPED,
    STAGE_SUCCEEDED,
    STAGE_TIMEOUT,
)

# === 资源限制默认值 ===
DEFAULT_BUILD_TIMEOUT_SECONDS = 3600
DEFAULT_BUILD_MEMORY_LIMIT_MB = 12288
DEFAULT_BUILD_CPU_LIMIT = 8
DEFAULT_MAX_BUILD_ATTEMPTS = 3  # 资源错误重试上限
DEFAULT_MAX_RETRY_ATTEMPTS = 3  # 可重试错误重试上限

# === 退避策略 ===
RETRY_BACKOFF_BASE_SECONDS = 30
RETRY_BACKOFF_MAX_SECONDS = 120
RETRY_BACKOFF_MULTIPLIER = 4  # 30s → 120s → 480s

# === AI 相关 ===
AI_MAX_NEED_MORE_CONTEXT_ROUNDS = 3  # NEED_MORE_CONTEXT 闭环最多 3 轮
AI_MAX_CONTEXT_LINES_PER_ROUND = 2000  # 每轮补取代码不超过 2000 行
AI_FAST_FILTER_CONFIDENCE_THRESHOLD = 0.9  # 快速过滤置信度阈值
AI_MAX_TOKENS_PER_CALL = 16384

# === 对象存储 ===
ARTIFACT_RETENTION_SHORT_DAYS = 30
ARTIFACT_RETENTION_LONG_DAYS = 180
ARTIFACT_RETENTION_PERMANENT = -1  # 永久

ARTIFACT_TYPES = {
    "SOURCE_ARCHIVE": "LONG",
    "BUILDFPLAN_JSON": "SHORT",
    "CODEQL_DATABASE": "LONG",
    "BUILD_LOG": "SHORT",
    "CODEQL_SARIF": "LONG",
    "EXTRACTED_FACTS": "SHORT",
    "EVIDENCE_BUNDLE": "LONG",
    "AI_REVIEW_RAW": "SHORT",
    "SCAN_REPORT": "PERMANENT",
    "DEBUG_BUNDLE": "SHORT",
}

# === SSE ===
SSE_EVENT_REDIS_TTL_SECONDS = 86400  # 24 小时

# === 缓存 ===
CODEQL_DB_CACHE_TTL_DAYS = 180
AI_REVIEW_CACHE_TTL_DAYS = 90

# === 增量扫描 ===
INCREMENTAL_CHANGE_THRESHOLD = 0.30  # 变更超过 30% 退化为全量

# === 安全画像评分 ===
SCORE_LEVEL_SAFE = "SAFE"
SCORE_LEVEL_LOW_RISK = "LOW_RISK"
SCORE_LEVEL_MEDIUM_RISK = "MEDIUM_RISK"
SCORE_LEVEL_HIGH_RISK = "HIGH_RISK"
SCORE_LEVEL_CRITICAL = "CRITICAL"

SCORE_RANGES = {
    SCORE_LEVEL_SAFE: (0, 24),
    SCORE_LEVEL_LOW_RISK: (25, 49),
    SCORE_LEVEL_MEDIUM_RISK: (50, 69),
    SCORE_LEVEL_HIGH_RISK: (70, 84),
    SCORE_LEVEL_CRITICAL: (85, 100),
}

# === Finding 状态 ===
FINDING_STATUS_OPEN = "OPEN"
FINDING_STATUS_FIXED = "FIXED"
FINDING_STATUS_REAPPEARED = "REAPPEARED"
FINDING_STATUS_FALSE_POSITIVE = "FALSE_POSITIVE"

FINDING_INSTANCE_STATUS_NEW = "NEW"
FINDING_INSTANCE_STATUS_RECURRING = "RECURRING"
FINDING_INSTANCE_STATUS_REAPPEARED = "REAPPEARED"
FINDING_INSTANCE_STATUS_RESOLVED = "RESOLVED"

# === AI verdict 枚举 ===
VERDICT_TRUE_POSITIVE = "TRUE_POSITIVE"
VERDICT_LIKELY_TRUE_POSITIVE = "LIKELY_TRUE_POSITIVE"
VERDICT_UNCERTAIN = "UNCERTAIN"
VERDICT_LIKELY_FALSE_POSITIVE = "LIKELY_FALSE_POSITIVE"
VERDICT_FALSE_POSITIVE = "FALSE_POSITIVE"
VERDICT_NEED_MORE_CONTEXT = "NEED_MORE_CONTEXT"
VERDICT_INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"

ALL_VERDICTS = frozenset({
    VERDICT_TRUE_POSITIVE,
    VERDICT_LIKELY_TRUE_POSITIVE,
    VERDICT_UNCERTAIN,
    VERDICT_LIKELY_FALSE_POSITIVE,
    VERDICT_FALSE_POSITIVE,
    VERDICT_NEED_MORE_CONTEXT,
    VERDICT_INSUFFICIENT_CONTEXT,
})

# === 构建质量 ===
BUILD_QUALITY_FULL_MANUAL = "FULL_MANUAL_BUILD"
BUILD_QUALITY_SUCCESSFUL_AUTOBUILD = "SUCCESSFUL_AUTOBUILD"
BUILD_QUALITY_PARTIAL = "PARTIAL_BUILD"
BUILD_QUALITY_NO_BUILD = "NO_BUILD_DEGRADED"
BUILD_QUALITY_FAILED = "BUILD_FAILED"

# === 构建模式 ===
BUILD_MODE_MANUAL = "MANUAL"
BUILD_MODE_AUTOBUILD = "AUTOBUILD"
BUILD_MODE_NO_BUILD = "NO_BUILD"

# === 严重度 ===
SEVERITY_INFO = "INFO"
SEVERITY_LOW = "LOW"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"
SEVERITY_CRITICAL = "CRITICAL"

SEVERITY_ORDER = [SEVERITY_INFO, SEVERITY_LOW, SEVERITY_MEDIUM, SEVERITY_HIGH, SEVERITY_CRITICAL]

# === check 结果六态（从 domain 重新导出方便使用）===
from app.domain.check_and_security import (  # noqa: E402
    CHECK_CRITICAL,
    CHECK_HIGH,
    CHECK_LOW,
    CHECK_MEDIUM,
    CHECK_NOT_CHECKED,
    CHECK_PASS,
)

# === 扫描模式 ===
SCAN_MODE_FULL = "FULL"
SCAN_MODE_INCREMENTAL = "INCREMENTAL"

# === 触发类型 ===
TRIGGER_MANUAL = "MANUAL"
TRIGGER_SCHEDULED = "SCHEDULED"
TRIGGER_CI = "CI"

# === 资源错误重试时的配额提升倍数 ===
RESOURCE_QUOTA_MULTIPLIER_OOM = 1.5
RESOURCE_QUOTA_MULTIPLIER_DISK = 2.0
RESOURCE_QUOTA_MULTIPLIER_TIMEOUT = 1.5
RESOURCE_QUOTA_OOM_CAP_MB = 24576  # OOM 提升上限 24GB
